# Generated by Django 5.2 on 2025-04-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('erro', 'Erro')], default='aguardando', max_length=20)),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.demandante')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atividade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsavel')),
            ],
            options={
                'unique_together': {('atividade', 'responsavel')},
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsaveis',
            field=models.ManyToManyField(through='app.AtividadeResponsavel', to='app.responsavel'),
        ),
        migrations.CreateModel(
            name='TipoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loginusuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo')),
            ],
            options={
                'unique_together': {('tipo', 'login')},
            },
        ),
    ]
