# Generated by Django 5.2 on 2025-04-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='responsaveis',
        ),
        migrations.AlterField(
            model_name='loginusuario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loginusuario',
            name='senha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status'),
        ),
    ]
