# Generated by Django 5.2 on 2025-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_status_remove_atividade_responsaveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='cor',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True),
        ),
    ]
