# Generated by Django 5.2 on 2025-05-03 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_status_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusuario',
            name='tipo',
            field=models.ForeignKey(default='Nada', on_delete=django.db.models.deletion.CASCADE, to='app.tipo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoLogin',
        ),
    ]
