# Generated by Django 5.2 on 2025-05-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loginusuario_tipo_delete_tipologin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginusuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'managed': False},
        ),
    ]
