# Generated by Django 5.2 on 2025-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_loginusuario_options_alter_tipo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginusuario',
            table='login_usuario',
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='tipo',
        ),
    ]
