# Generated by Django 5.2 on 2025-05-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_loginusuario_table_alter_tipo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='demandante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'managed': False},
        ),
    ]
