# Generated by Django 5.2 on 2025-05-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_atividade_options_alter_demandante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividade',
            table='atividade',
        ),
        migrations.AlterModelTable(
            name='demandante',
            table='demandante',
        ),
        migrations.AlterModelTable(
            name='responsavel',
            table='responsavel',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
