# Generated by Django 5.2 on 2025-05-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_atividade_table_alter_demandante_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividaderesponsavel',
            options={'managed': False},
        ),
    ]
