# Generated by Django 5.2 on 2025-05-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_atividaderesponsavel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividaderesponsavel',
            table='atividade_responsavel',
        ),
    ]
